# Generated by Django 2.1.1 on 2019-01-25 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarecived',
            name='ImageSavedUrl',
        ),
        migrations.AddField(
            model_name='datarecived',
            name='ImageFile',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='datarecived',
            name='Create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
